### PR TITLE
Add midnight coding to feeds

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by fschulze** [comment]
Unfortunately http://nicoddemus.github.io/tag/pytest/ doesn't work, since it is no feed. Do you have a way to create a feed for tags, or should we just use the global http://nicoddemus.github.io/atom.xml?

**Comment by nicoddemus** [comment]
This seems to work: http://nicoddemus.github.io/tag/pytest/atom.xml

My question is if this should be added to the `link=` property or the "grouping" in `[]`?

**Comment by fschulze** [comment]
The grouping, as it says at the top of the file:

```
 # [URL-TO-FEED (RSS, ATOM, etc.)]
```

**Comment by nicoddemus** [comment]
Thanks! :grin:

**Pull request merged**
